/**
 * Entry Point
 * 
 * Expo Router entry file.
 * - Auto-generated by Expo to handle navigation setup.
 * - Imports the router entry for classic or file-based routing.
 */
// This is aliased to another location when server components are enabled.
// We use this intermediate file to avoid issues with aliases not applying to package.json main field resolution.
import 'expo-router/entry-classic';
